# Generated by Django 4.1.7 on 2023-03-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='curso',
        ),
    ]
